cnn_code_4_classes/EcgApp/EcgApp/Models/ErrorViewModel.cs
using System;

namespace EcgApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

cnn_code_4_classes/EcgApp/EcgApp/Models/Record.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EcgApp.Models
{
    public class Record
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string RecordPath { get; set; }
        [Required]
        public string TypeN { get; set; }
        [Required]
        public string TypeRBBB { get; set; }
        [Required]
        public string TypeAFIB { get; set; }
        [Required]
        public string TypeB { get; set; }

    }
}

cnn_code_4_classes/EcgApp/EcgApp/ViewModels/RecordViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EcgApp.ViewModels
{
    public class RecordViewModel
    {
        [Required]
        public string Name { get; set; }
        public IFormFile RecordFile { get; set; }

        [Required]
        public List<string> TypeN { get; set; }
        [Required]
        public List<string> TypeRBBB { get; set; }
        [Required]
        public List<string> TypeAFIB { get; set; }
        [Required]
        public List<string> TypeB { get; set; }
    }
}

cnn_code_4_classes/EcgApp/EcgApp/Controllers/ChooseEcgRecordController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using EcgApp.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;
using System.Collections;
using System.Security.Cryptography.Xml;

using System.Web;


namespace EcgApp.Controllers
{
    public class ChooseEcgRecordController : Controller
    {
        private readonly IWebHostEnvironment hostingEnvironment;

        public ChooseEcgRecordController(IWebHostEnvironment hostingEnvironment)
        {
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: /<controller>/
        public IActionResult ChooseEcgRecord()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ok(RecordViewModel model)
        {
            string uniqueFileName = null;
            string filePath = null;

            if (model.RecordFile != null)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "records");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.RecordFile.FileName;
                filePath = Path.Combine(uploadsFolder, uniqueFileName);
                model.RecordFile.CopyTo(new FileStream(filePath, FileMode.Create));
            }

            //execute .py
            // create process info
            var psi = new ProcessStartInfo();
            psi.FileName = @"C:\Users\Professional\AppData\Local\Programs\Python\Python36\python.exe";

            //provide script and argument
            var script = @"C:\Users\Professional\Desktop\1studing\CourseWork3\course_work_app\Course_work\cnn_code_4_classes\predicting_4.py";
            var arg = model.RecordFile.FileName.Split(".")[0];

            psi.Arguments = $"{script} {arg}";

            //process configuration
            psi.UseShellExecute = false;
            psi.CreateNoWindow = true;
            psi.RedirectStandardOutput = true;
            psi.RedirectStandardError = true;

            //execute process and get output
            var errors = "";
            string results = "";

            using (var process = Process.Start(psi))
            {
                errors = process.StandardError.ReadToEnd();
                results = process.StandardOutput.ReadToEnd();
                //Console.WriteLine(results);
            }

            string data = null;
            using (var reader = new StreamReader(model.RecordFile.OpenReadStream()))
            {
                while (reader.Peek() >= 0)
                    data += reader.ReadLine();
                //data = reader.ReadToEnd();
            }

            List<int> listValues = new List<int>();

            string[] numbers = Regex.Split(data, @"\D+");
            foreach (string value in numbers)
            {
                if (!string.IsNullOrEmpty(value))
                {
                    int i = int.Parse(value);
                    listValues.Add(i);
                }
            }

            ViewBag.VALUES = listValues;
            ViewBag.RESULT = model.RecordFile.FileName;

            string[] allResults = results.Split(' ');
            string resN = allResults[2] + "%";
            string resRBBB = allResults[4] + "%";
            string resB = allResults[6] + "%";
            string resAFIB = allResults[8] + "%";

            ViewBag.N = resN;
            ViewBag.RBBB = resRBBB;
            ViewBag.B = resB;
            ViewBag.AFIB = resAFIB;


            string lineFromFile = "";
            FileStream fileStream = new FileStream(@"C:\Users\Professional\Desktop\1studing\CourseWork3\course_work_app\Course_work\cnn_code_4_classes\EcgApp\EcgApp\App_Data\sectorsFile.txt", FileMode.Open);
            using (StreamReader reader = new StreamReader(fileStream))
            {
                lineFromFile = reader.ReadLine();
            }

            string[] allSectors = lineFromFile.Split(';');
            List<string> listN = new List<string>();
            List<string> listRBBB = new List<string>();
            List<string> listB = new List<string>();
            List<string> listAFIB = new List<string>();
            for (int i = 0; i < allSectors.Length - 1; i++)
            {
                string[] val = allSectors[i].Split(':');
                if (val[2] == "0")
                    listN.Add(val[0] + ", " + val[1] + ";");
                else
                    if (val[2] == "1")
                    listRBBB.Add(val[0] + ", " + val[1] + ";");
                else
                    if (val[2] == "2")
                    listB.Add(val[0] + ", " + val[1] + ";");
                else
                    if (val[2] == "3")
                    listAFIB.Add(val[0] + ", " + val[1] + ";");

            }

            model.TypeN = listN;
            model.TypeRBBB = listRBBB;
            model.TypeB = listB;
            model.TypeAFIB = listAFIB;

            ViewBag.listN = listN;
            ViewBag.listRBBB = listRBBB;
            ViewBag.listB = listB;
            ViewBag.listAFIB = listAFIB;

            return View();

        }
    }
}

cnn_code_4_classes/EcgApp/EcgApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EcgApp.Models;

namespace EcgApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

cnn_code_4_classes/EcgApp/EcgApp/Controllers/ShowResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EcgApp.Controllers
{
    public class ShowResultsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

cnn_code_4_classes/EcgApp/EcgApp/Views/ChooseEcgRecord/ChooseEcgRecord.cshtml
@model EcgApp.ViewModels.RecordViewModel

@{
    ViewData["Title"] = "Choose ECG record";
}
<h1>@ViewData["Title"]</h1>

<p></p>

<form enctype="multipart/form-data" asp-controller="ChooseEcgRecord" asp-action="Ok">
    <div class="form-group row">
        <label asp-for="RecordFile" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input asp-for="RecordFile" class="form-control custom-file-input">
                <label class="custom-file-label">Choose file..</label>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Ok</button>
        </div>
    </div>

    @section Scripts {
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                })
            })
        </script>
    }
</form>

cnn_code_4_classes/EcgApp/EcgApp/Views/ChooseEcgRecord/Ok.cshtml
@{
    ViewData["Title"] = "Ok";
}
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
</head>
<body>
    <div style="float:right;">
        <div class="btn-group" style="width:100%">
            <button OnClick="buttonN();" style="width:25%">N</button>
            <button OnClick="buttonRBBB();" style="width:25%">RBBB</button>
            <button OnClick="buttonB();" style="width:25%">B</button>
            <button OnClick="buttonAFIB();" style="width:25%">AFIB</button>
        </div>

        <div class="sectorsWrapper" style="height: 400px; width: 300px; overflow-x:auto; ">
            <div id="sectors" style="float:initial; height: 400px; width: 100px;">
                <table border='1' id="mytable" style="width: 280px;">
                    <thead style="width: 280px;">
                        <tr>Pathology coordinates</tr>
                    </thead>
                    <tbody id="tb0">
                    </tbody>               
                </table>
            </div>
        </div>
    </div>
    <div class="chartWrapper" style="height: 410px; width: 800px; overflow-x:auto; position:relative;">
        <div id="chartContainer" style="height: 390px; width: 9000px;"></div>
    </div>

    <div id="patologies">
        <ul>
            <li style="display: inline;">Normal sinus rhythm:&nbsp @Html.Raw(Json.Serialize(ViewBag.N)) &nbsp&nbsp&nbsp</li>
            <li style="display: inline;">Normal sinus rhythm with right bundle branch block:&nbsp @Html.Raw(Json.Serialize(ViewBag.RBBB)) &nbsp&nbsp&nbsp</li>
        </ul>
        <ul>
            <li style="display: inline;">Ventricular bigeminy:&nbsp @Html.Raw(Json.Serialize(ViewBag.B)) &nbsp&nbsp&nbsp</li>
            <li style="display: inline;">Atrial fibrillation:&nbsp @Html.Raw(Json.Serialize(ViewBag.AFIB)) &nbsp&nbsp&nbsp</li>
        </ul>
    </div>

    <script>

        var xAxisStripLinesArray = [];
        var yAxisStripLinesArray = [];
        var dps = [];

        var dataPointsArray = @Html.Raw(Json.Serialize(ViewBag.VALUES));
        var results_temp = @Html.Raw(Json.Serialize(ViewBag.RESULT));

        var chart = new CanvasJS.Chart("chartContainer",
            {
                zoomEnabled: true,
                title: {
                    text: "ECG Report",
                },
                subtitles: [{
                    text: "ECG Report from record № " + results_temp,
                    horizontalAlign: "left",
                },
                {
                    text: "Duration: 30 min ",
                    horizontalAlign: "left",
                },
                ],
                axisY: {
                    stripLines: yAxisStripLinesArray,
                    gridThickness: 2,
                    gridColor: "#DC74A5",
                    lineColor: "#DC74A5",
                    tickColor: "#DC74A5",
                    labelFontColor: "#DC74A5",
                },
                axisX: {
                    stripLines: xAxisStripLinesArray,
                    gridThickness: 2,
                    gridColor: "#DC74A5",
                    lineColor: "#DC74A5",
                    tickColor: "#DC74A5",
                    labelFontColor: "#DC74A5",
                },
                data: [
                    {
                        //type: "spline",
                        type: "line",
                        color: "black",
                        dataPoints: dps
                    }
                ]
            });

        addDataPointsAndStripLines();
        chart.render();

        function addDataPointsAndStripLines() {
            //dataPoints
            for (var i = 0; i < dataPointsArray.length; i += 100)
            {
                dps.push({x: i * 1, y: dataPointsArray[i] });
            }
            //StripLines
            for (var i = 0; i < 3000; i = i + 100) {
                if (i % 1000 != 0)
                    yAxisStripLinesArray.push({ value: i, thickness: 0.7, color: "#DC74A5" });
            }
            for (var i = 0; i < dataPointsArray.length; i = i + 100)
            {
                if (i % 200 != 0)
                    xAxisStripLinesArray.push({ value: i, thickness: 0.7, color: "#DC74A5" });
            }
        }

        var listN = @Html.Raw(Json.Serialize(ViewBag.listN));
        var listRBBB = @Html.Raw(Json.Serialize(ViewBag.listRBBB));
        var listB = @Html.Raw(Json.Serialize(ViewBag.listB));
        var listAFIB = @Html.Raw(Json.Serialize(ViewBag.listAFIB));

        function buttonN()
        {        
            var tabBody = document.getElementById("tb0");  
            $("tbody").children().remove();

                for (var i = 0; i < listN.length; i++) {
                    row = document.createElement("tr");
                    cell = document.createElement("td");
                    textnode = document.createTextNode(listN[i]);
                    cell.appendChild(textnode);
                    row.appendChild(cell);
                    tabBody.appendChild(row);
                }
        }

        function buttonRBBB()
        {
           
            var tabBody = document.getElementById("tb0");
            $("tbody").children().remove();

                for (var i = 0; i < listRBBB.length; i++) {
                    row = document.createElement("tr");
                    cell = document.createElement("td");
                    textnode = document.createTextNode(listRBBB[i]);
                    cell.appendChild(textnode);
                    row.appendChild(cell);
                    tabBody.appendChild(row);
                }
        }

        function buttonB()
        {
          
            var tabBody = document.getElementById("tb0");
            $("tbody").children().remove();

                for (var i = 0; i < listB.length; i++) {
                    row = document.createElement("tr");
                    cell = document.createElement("td");
                    textnode = document.createTextNode(listB[i]);
                    cell.appendChild(textnode);
                    row.appendChild(cell);
                    tabBody.appendChild(row);
                }
        }

        function buttonAFIB()
        {
           
            var tabBody = document.getElementById("tb0"); 
            $("tbody").children().remove();

                for (var i = 0; i < listAFIB.length; i++) {
                    row = document.createElement("tr");
                    cell = document.createElement("td");
                    textnode = document.createTextNode(listAFIB[i]);
                    cell.appendChild(textnode);
                    row.appendChild(cell);
                    tabBody.appendChild(row);
                }
        }

    </script>
</body>
</html>

cnn_code_4_classes/EcgApp/EcgApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">Система анализа электрокардиограмм</h1>
    </div>
    <p>Система предоставляет возможность:</p>
    <ul>
        <li>загрузить файл электрокардиограммы с компьютера;</li>
        <li>просмотреть отчёт в форме графика;</li>
        <li>в % получить вероятность нахождения определённых патологий на экг-записи;</li>
        <li>получить координаты расположения каждой патологии на экг-записи.</li>
    </ul>
    @*<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@

cnn_code_4_classes/EcgApp/EcgApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcgApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EcgApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ChooseEcgRecord" asp-action="ChooseEcgRecord">Choose ECG record</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EcgApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>